### ISSUE TITLE
Exporting Text Function Missing?

### ISSUE THREAD

**Issue by hescrotating** [MontagueM/Charm#17] opened 2022-07-17 18:00 UTC
The export option for text  strings seems to be red and unable to be used under any circumstances. Unsure if I'm missing something or the feature isn't working as intended. 
![exporting text](https://user-images.githubusercontent.com/109479786/179418740-93a45156-4029-4886-acf0-addd2ca934ff.png)

**Comment by MontagueM** [comment] 2022-07-17 18:17
duplicate of #1

**Closed by MontagueM** 2022-07-17 18:17 UTC
Labels: duplicate
